spring.application.name=project-inventory-api

spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jakarta.persistence.jdbc.url=jdbc:postgresql://postgres:5432/mydb
